name: crypto-assist
cognito:
  domain: crypto-assist-dev
  googleEnabled: true
  web:
    callbackUrls:
      - https://d3apwa6oetv5aj.cloudfront.net/auth/callback
      - http://localhost:5173/auth/callback
    logoutUrls:
      - https://d3apwa6oetv5aj.cloudfront.net
      - http://localhost:5173
  mobile:
    callbackUrls:
      - crypto-assist://callback
    logoutUrls:
      - crypto-assist://logout

web:
  cloudFront: true
