name: crypto-assist

cognito:
  domain: crypto-assist
  googleEnabled: true
  web:
    callbackUrls:
      - https://d3nab81epd8vp1.cloudfront.net/auth/callback
      - http://localhost:5173/auth/callback
    logoutUrls:
      - https://d3nab81epd8vp1.cloudfront.net
      - http://localhost:5173
  mobile:
    callbackUrls:
      - crypto-assist://callback
    logoutUrls:
      - crypto-assist://logout

storage:
  backupBucket: true

web:
  cloudFront: true
