name: crypto-assist
cognito:
  domain: crypto-assist-stg
  googleEnabled: false
  web:
    callbackUrls:
      - https://d2xhrsd3sjdaob.cloudfront.net/auth/callback
      - http://localhost:5173/auth/callback
    logoutUrls:
      - https://d2xhrsd3sjdaob.cloudfront.net
      - http://localhost:5173
  mobile:
    callbackUrls:
      - crypto-assist://callback
    logoutUrls:
      - crypto-assist://logout

web:
  cloudFront: true
